"""Regenerate web/src/assets/support_cards.json from the game's master database.

The "Borrowing Support Card" picker in the web UI reads its card list from
web/src/assets/support_cards.json. That file is generated by this script from
master.mdb, the SQLite database the Global client keeps its master data in, so
the titles match the game's own English text exactly - the bot OCRs the card
title on the borrow screen and fuzzy-matches it against the name stored in the
task, so a title that differs from the game's wording breaks card selection.

Run this after a game update adds or renames support cards:

    py -3.10 export_support_cards.py
    cd web && npx vite build          # the JSON is bundled at build time

master.mdb lives in the Umamusume client's data folder, by default
%USERPROFILE%\\AppData\\LocalLow\\Cygames\\Umamusume\\master\\master.mdb.
Pass --db to point at another copy (a different PC, an emulator pull). The
database is only ever opened read-only.

Schema notes (master.mdb, Global client):
  support_card_data  one row per card; command_id is the training type and
                     rarity is 1=R, 2=SR, 3=SSR
  text_data          localized strings keyed by (category, index); for a card
                     id, category 76 holds the bracketed title and category 77
                     the character name (category 75 is the two joined)

Friend and group cards (support_card_type 2 and 3) both have command_id 0 and
are exported as type "friend" - the picker lists them in one Friend tab.
"""
import argparse
import json
import os
import sqlite3

DEFAULT_DB = os.path.join(os.path.expanduser("~"), "AppData", "LocalLow", "Cygames",
                          "Umamusume", "master", "master.mdb")
DEFAULT_OUT = os.path.join("web", "src", "assets", "support_cards.json")

# command_id -> training type. 101/102/105/106 confirmed against known Global
# cards (Fire at My Heels, Wild Rider, Piece of Mind, Wave of Gratitude);
# 103 is guts by elimination and matches the known guts roster (BNWinner!,
# Fairest Fleur). 0 is used by friend and group cards, which train nothing.
TYPE_BY_COMMAND = {101: "speed", 102: "power", 103: "guts", 105: "stamina", 106: "wit", 0: "friend"}
RARITY = {1: "R", 2: "SR", 3: "SSR"}
RARITY_ORDER = {"SSR": 0, "SR": 1, "R": 2}

QUERY = ('SELECT s.id, t76.text, t77.text, s.command_id, s.rarity '
         'FROM support_card_data s '
         'JOIN text_data t76 ON t76.category=76 AND t76."index"=s.id '
         'JOIN text_data t77 ON t77.category=77 AND t77."index"=s.id '
         'ORDER BY s.id')


def read_cards(db_path):
    uri = "file:" + db_path.replace(os.sep, "/") + "?mode=ro"
    con = sqlite3.connect(uri, uri=True)
    try:
        cards = []
        for card_id, title, chara, command_id, rarity in con.execute(QUERY):
            name = title.strip()
            if name.startswith("[") and name.endswith("]"):
                name = name[1:-1]
            cards.append({
                "id": card_id,
                "name": name,
                "desc": chara.strip(),
                "type": TYPE_BY_COMMAND.get(command_id, "friend"),
                "rarity": RARITY.get(rarity, "?"),
            })
    finally:
        con.close()
    cards.sort(key=lambda c: (RARITY_ORDER.get(c["rarity"], 9), c["name"]))
    return cards


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--db", default=DEFAULT_DB, help="path to master.mdb")
    parser.add_argument("--out", default=DEFAULT_OUT, help="path to the JSON to write")
    args = parser.parse_args()

    if not os.path.exists(args.db):
        raise SystemExit(f"master.mdb not found at {args.db}\n"
                         f"Launch the game once to download master data, or pass --db.")

    cards = read_cards(args.db)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(cards, f, ensure_ascii=False, indent=1)

    by_type = {}
    for c in cards:
        by_type[c["type"]] = by_type.get(c["type"], 0) + 1
    by_rarity = {r: sum(1 for c in cards if c["rarity"] == r) for r in ("SSR", "SR", "R")}
    print(f"wrote {len(cards)} cards to {args.out}")
    print(f"  by rarity: {by_rarity}")
    print(f"  by type:   {by_type}")


if __name__ == "__main__":
    main()
